spring:
       datasource:
                  url: jdbc:mysql://localhost:3306/dp?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&tinyInt1isBit=false
                  username: root
                  password: Op009oP!
spring.jpa:
           hibernate.ddl-auto: validate
           show-sql: false




blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005